# Generated by Django 5.2.3 on 2025-07-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ruolo', models.CharField(max_length=100)),
                ('descrizione_breve', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
                ('ordine', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Membro del Team',
                'verbose_name_plural': 'Membri del Team',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Servizio')),
                ('slug', models.SlugField(blank=True, help_text='Slug per URL puliti. Lascia vuoto per generare automaticamente.', unique=True)),
                ('descrizione_breve', models.TextField(help_text='Breve descrizione per la lista servizi o homepage.', verbose_name='Descrizione Breve')),
                ('descrizione_completa', models.TextField(help_text='Descrizione dettagliata per la pagina del servizio.', verbose_name='Descrizione Completa')),
                ('immagine_principale', models.ImageField(help_text='Immagine per la copertina del servizio.', upload_to='servizi_immagini/', verbose_name='Immagine Principale')),
                ('icona_svg_code', models.TextField(blank=True, help_text="Codice SVG dell'icona del servizio (opzionale). In alternativa, usa le icone del tema.", verbose_name='Codice SVG Icona')),
                ('ordine_visualizzazione', models.IntegerField(default=0, help_text='Numero per ordinare i servizi (servizi con numero più basso vengono prima).', verbose_name='Ordine di Visualizzazione')),
                ('attivo', models.BooleanField(default=True, help_text='Indica se il servizio è visibile sul sito.', verbose_name='Servizio Attivo')),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['ordine_visualizzazione', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ServizioImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='servizi_galleria/')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Testo Alt Immagine')),
                ('ordine', models.IntegerField(default=0)),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_immagini', to='main.servizio')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
