# Generated by Django 5.2.3 on 2025-07-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_membroteam_servizio_servizioimmagine_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoOfficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text="Un titolo breve per la foto (es. 'La nostra cabina di verniciatura').", max_length=100)),
                ('descrizione', models.TextField(blank=True, help_text="Una descrizione opzionale per fornire maggiori dettagli sull'immagine.")),
                ('foto', models.ImageField(help_text="Carica l'immagine per la galleria.", upload_to='officina/')),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Numero per ordinare le foto nella galleria (0 per primo).')),
            ],
            options={
                'verbose_name': 'Foto Officina',
                'verbose_name_plural': 'Foto Officina',
                'ordering': ['ordine'],
            },
        ),
    ]
