# Generated by Django 5.2.3 on 2025-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fotoofficina_max_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('immagine', models.ImageField(upload_to='certificazioni/')),
                ('ordine', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificazione',
                'verbose_name_plural': 'Certificazioni',
                'ordering': ['ordine'],
            },
        ),
    ]
