# Generated by Django 5.2.3 on 2025-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_certificazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('immagine', models.ImageField(upload_to='partners/')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('in_homepage', models.BooleanField(default=False, verbose_name='Mostra in homepage')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partner',
                'ordering': ['ordine'],
            },
        ),
    ]
