# Generated by Django 5.2.3 on 2025-07-12 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoChiaveServizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.CharField(max_length=255, verbose_name='Testo del Punto Chiave')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine di Visualizzazione')),
                ('servizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punti_chiave', to='main.servizio', verbose_name='Servizio di Riferimento')),
            ],
            options={
                'verbose_name': 'Punto Chiave del Servizio',
                'verbose_name_plural': 'Punti Chiave dei Servizi',
                'ordering': ['ordine', 'testo'],
            },
        ),
    ]
