# Generated by Django 5.2.3 on 2025-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_puntochiaveservizio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servizio',
            name='messaggio_whatsapp',
            field=models.TextField(blank=True, help_text="Il testo che l'utente troverà precompilato su WhatsApp. Usa [NOME_SERVIZIO] per inserire dinamicamente il nome del servizio.", verbose_name='Messaggio WhatsApp Precompilato'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='mostra_bottone_whatsapp',
            field=models.BooleanField(default=False, help_text='Seleziona per mostrare un pulsante WhatsApp specifico per questo servizio.', verbose_name='Mostra bottone WhatsApp?'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='numero_whatsapp',
            field=models.CharField(blank=True, help_text='Inserisci il numero di telefono completo (es. 41765322296) a cui inviare il messaggio.', max_length=20, verbose_name='Numero WhatsApp'),
        ),
        migrations.AddField(
            model_name='servizio',
            name='testo_bottone_whatsapp',
            field=models.CharField(blank=True, default='Valutazione via WhatsApp', help_text="Il testo che apparirà sul pulsante (es. 'Richiedi un preventivo').", max_length=100, verbose_name='Testo del bottone WhatsApp'),
        ),
    ]
