# Generated by Django 5.2.3 on 2025-08-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_servizio_messaggio_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servizio',
            name='messaggio_whatsapp',
            field=models.CharField(blank=True, help_text="Il testo che l'utente troverà precompilato su WhatsApp. Usa [NOME_SERVIZIO] per inserire dinamicamente il nome del servizio.", max_length=500, verbose_name='Messaggio WhatsApp Precompilato'),
        ),
    ]
