# Generated by Django 5.2.3 on 2025-12-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_servizio_messaggio_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tipo_richiesta', models.CharField(choices=[('Preventivo riparazione', 'Preventivo riparazione'), ('Servizi generali', 'Servizi generali'), ('Informazioni restauro', 'Informazioni restauro'), ('Altro', 'Altro')], max_length=50)),
                ('messaggio', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
