# Generated by Django 5.2.3 on 2025-12-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contatto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatto',
            options={'ordering': ['-data_invio'], 'verbose_name': 'Messaggi Contatti', 'verbose_name_plural': 'Messaggi Contatti'},
        ),
    ]
