# Generated by Django 5.2.3 on 2025-07-03 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restauro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255, verbose_name='Titolo del Progetto')),
                ('slug', models.SlugField(blank=True, help_text='Slug per URL puliti. Lascia vuoto per generare automaticamente.', unique=True)),
                ('marca_veicolo', models.CharField(blank=True, max_length=100, verbose_name='Marca del Veicolo')),
                ('modello_veicolo', models.CharField(blank=True, max_length=100, verbose_name='Modello del Veicolo')),
                ('anno_veicolo', models.IntegerField(blank=True, null=True, verbose_name='Anno del Veicolo')),
                ('descrizione_breve', models.TextField(help_text='Breve riassunto per la lista portfolio.', verbose_name='Descrizione Breve')),
                ('descrizione_dettagliata', models.TextField(help_text='Dettagli completi del processo di restauro.', verbose_name="Descrizione Dettagliata dell'Intervento")),
                ('foto_prima', models.ImageField(upload_to='restauri_prima_dopo/', verbose_name='Foto Prima del Restauro')),
                ('foto_dopo', models.ImageField(upload_to='restauri_prima_dopo/', verbose_name='Foto Dopo il Restauro')),
                ('tipo_veicolo', models.CharField(choices=[('auto_epoca', "Auto d'Epoca"), ('moto', 'Moto'), ('progetti_speciali', 'Progetti Speciali / Modifiche'), ('altro', 'Altro')], default='auto_epoca', max_length=50, verbose_name='Tipo di Veicolo')),
                ('data_completamento', models.DateField(blank=True, null=True, verbose_name='Data Completamento Progetto')),
                ('ordine_visualizzazione', models.IntegerField(default=0, help_text='Numero per ordinare i progetti (più basso = prima).', verbose_name='Ordine di Visualizzazione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Visibile sul Sito')),
            ],
            options={
                'verbose_name': 'Progetto di Restauro',
                'verbose_name_plural': 'Progetti di Restauro',
                'ordering': ['ordine_visualizzazione', '-data_completamento'],
            },
        ),
        migrations.CreateModel(
            name='RestauroImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='restauri_galleria/')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Testo Alt Immagine')),
                ('descrizione', models.TextField(blank=True, verbose_name="Descrizione dell'Immagine")),
                ('ordine', models.IntegerField(default=0)),
                ('restauro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_processo', to='restauri.restauro')),
            ],
            options={
                'ordering': ['ordine'],
            },
        ),
    ]
