# Generated by Django 5.2.3 on 2025-07-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauro',
            name='in_evidenza',
            field=models.BooleanField(default=False, help_text='Seleziona per mostrare questo progetto nella sezione principale della pagina restauri.', verbose_name='In Evidenza'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='descrizione_breve',
            field=models.TextField(help_text='Breve riassunto per le anteprime.', verbose_name='Descrizione Breve'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='descrizione_dettagliata',
            field=models.TextField(help_text='Dettagli completi del processo di restauro.', verbose_name='Descrizione Dettagliata'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='slug',
            field=models.SlugField(blank=True, help_text="Lascia vuoto per generare automaticamente dall'URL.", unique=True),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='tipo_veicolo',
            field=models.CharField(choices=[('auto-epoca', "Auto d'Epoca"), ('moto', 'Moto'), ('progetti-speciali', 'Progetti Speciali'), ('altro', 'Altro')], default='auto-epoca', max_length=50, verbose_name='Tipo di Progetto'),
        ),
    ]
