# Generated by Django 5.2.3 on 2025-07-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0002_restauro_in_evidenza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauro',
            name='foto_copertina',
            field=models.ImageField(blank=True, help_text="Immagine specifica da usare come copertina. Se lasciata vuota, verrà usata la 'Foto Dopo'.", null=True, upload_to='restauri_copertine/', verbose_name='Immagine di Copertina dedicata'),
        ),
    ]
