# Generated by Django 5.2.3 on 2025-07-10 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0004_alter_restauro_foto_copertina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauro',
            name='descrizione_breve',
            field=models.TextField(help_text="Breve riassunto per le anteprime e l'introduzione.", verbose_name='Descrizione Breve'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='descrizione_dettagliata',
            field=models.TextField(blank=True, help_text="Descrizione generale del progetto. I dettagli specifici andranno nelle singole 'Fasi di Lavoro'.", verbose_name='Descrizione Generale'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='foto_copertina',
            field=models.ImageField(help_text='Immagine principale mostrata nelle liste e anteprime.', upload_to='restauri/copertine/', verbose_name='Immagine di Copertina'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='foto_dopo',
            field=models.ImageField(blank=True, null=True, upload_to='restauri/prima_dopo/', verbose_name='Foto Dopo il Restauro'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='foto_prima',
            field=models.ImageField(blank=True, null=True, upload_to='restauri/prima_dopo/', verbose_name='Foto Prima del Restauro'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='slug',
            field=models.SlugField(blank=True, help_text='Lascia vuoto per generare automaticamente dal titolo.', unique=True),
        ),
        migrations.CreateModel(
            name='FaseLavoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(help_text="Es: 'Smontaggio e Lattoneria', 'Verniciatura', 'Restauro Interni'", max_length=200, verbose_name='Titolo della Fase')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione Attività Svolte')),
                ('ordine', models.PositiveIntegerField(default=0, help_text='Per ordinare le fasi cronologicamente (0, 1, 2...).', verbose_name='Ordine di Visualizzazione')),
                ('restauro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasi_lavoro', to='restauri.restauro', verbose_name='Progetto di Riferimento')),
            ],
            options={
                'verbose_name': 'Fase di Lavoro',
                'verbose_name_plural': 'Fasi di Lavoro',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ImmagineFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='restauri/fasi/', verbose_name='Immagine')),
                ('alt_text', models.CharField(blank=True, help_text="Breve descrizione dell'immagine per l'accessibilità e i motori di ricerca.", max_length=255, verbose_name='Testo Alternativo (SEO)')),
                ('ordine', models.PositiveIntegerField(default=0, verbose_name='Ordine Immagine')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini_fase', to='restauri.faselavoro', verbose_name='Fase di Riferimento')),
            ],
            options={
                'verbose_name': 'Immagine della Fase',
                'verbose_name_plural': 'Immagini della Fase',
                'ordering': ['ordine'],
            },
        ),
        migrations.DeleteModel(
            name='RestauroImmagine',
        ),
    ]
