# Generated by Django 5.2.3 on 2025-09-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0005_alter_restauro_descrizione_breve_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestauriImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='restauri_galleria/')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Testo Alt Immagine')),
                ('ordine', models.IntegerField(default=0)),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_foto', to='restauri.restauro')),
            ],
            options={
                'verbose_name': 'Immagine Veicolo',
                'verbose_name_plural': 'Immagini Veicolo',
                'ordering': ['ordine'],
            },
        ),
    ]
