# Generated by Django 5.2.3 on 2025-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0006_restauriimmagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauro',
            name='logo_macchina',
            field=models.ImageField(blank=True, null=True, upload_to='restauri/copertine/', verbose_name='Logo veicolo'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='tipo_veicolo',
            field=models.CharField(choices=[('auto-epoca', "Auto d'Epoca"), ('moto-epoca', 'Moto d’epoca'), ('progetti-speciali', 'Progetti speciali'), ('altro', 'Altro')], default='auto-epoca', max_length=50, verbose_name='Tipo di Progetto'),
        ),
    ]
