# Generated by Django 5.2.3 on 2025-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0007_restauro_logo_macchina_alter_restauro_tipo_veicolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauro',
            name='tipo_veicolo',
            field=models.CharField(choices=[('auto-epoca', "Auto d'epoca"), ('moto-epoca', 'Moto d’epoca'), ('progetti-speciali', 'Progetti speciali'), ('altro', 'Altro')], default='auto-epoca', max_length=50, verbose_name='Tipo di Progetto'),
        ),
    ]
