# Generated by Django 5.2.3 on 2025-12-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0008_alter_restauro_tipo_veicolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauro',
            name='carrozzeria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Carrozzeria'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='cilindrata',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cilindrata'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='dimensioni',
            field=models.CharField(blank=True, help_text='Esempio: 4080 × 1600 × 1300 mm', max_length=100, null=True, verbose_name='Dimensioni (L × P × A)'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='freni',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Freni'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='motore',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motore'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='peso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='sospensioni',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Sospensioni'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='trasmissione',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trasmissione'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='velocita_massima',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocità massima'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='marca_veicolo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Veicolo'),
        ),
        migrations.AlterField(
            model_name='restauro',
            name='modello_veicolo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modello del Veicolo'),
        ),
    ]
