# Generated by Django 5.2.3 on 2025-12-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0009_restauro_carrozzeria_restauro_cilindrata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauro',
            name='potenza_massima',
            field=models.CharField(blank=True, max_length=100, verbose_name='Potenza massima'),
        ),
        migrations.AddField(
            model_name='restauro',
            name='trazione',
            field=models.CharField(blank=True, max_length=100, verbose_name='Trazione'),
        ),
    ]
