# Generated by Django 5.2.3 on 2026-02-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restauri', '0010_restauro_potenza_massima_restauro_trazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauro',
            name='versione_veicolo',
            field=models.CharField(blank=True, null=True, verbose_name='Versione Veicolo'),
        ),
    ]
