# Generated by Django 5.2.3 on 2025-07-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeicoloInVendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modello', models.CharField(max_length=100, verbose_name='Modello')),
                ('slug', models.SlugField(blank=True, help_text='Slug per URL puliti. Lascia vuoto per generare automaticamente.', unique=True)),
                ('anno', models.IntegerField(verbose_name='Anno di Immatricolazione')),
                ('chilometraggio', models.IntegerField(verbose_name='Chilometraggio (KM)')),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo (CHF)')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione del Veicolo')),
                ('tipo_carburante', models.CharField(choices=[('benzina', 'Benzina'), ('diesel', 'Diesel'), ('elettrico', 'Elettrico'), ('ibrido', 'Ibrido'), ('gpl', 'GPL'), ('metano', 'Metano')], max_length=50, verbose_name='Tipo Carburante')),
                ('tipo_cambio', models.CharField(choices=[('manuale', 'Manuale'), ('automatico', 'Automatico')], max_length=50, verbose_name='Tipo Cambio')),
                ('trazione', models.CharField(choices=[('anteriore', 'Anteriore'), ('posteriore', 'Posteriore'), ('integrale', 'Integrale')], max_length=50, verbose_name='Trazione')),
                ('colore_esterno', models.CharField(blank=True, max_length=50, verbose_name='Colore Esterno')),
                ('colore_interno', models.CharField(blank=True, max_length=50, verbose_name='Colore Interno')),
                ('numero_porte', models.IntegerField(blank=True, null=True, verbose_name='Numero Porte')),
                ('numero_posti', models.IntegerField(blank=True, null=True, verbose_name='Numero Posti')),
                ('potenza_cv', models.IntegerField(blank=True, null=True, verbose_name='Potenza (CV)')),
                ('cilindrata', models.IntegerField(blank=True, null=True, verbose_name='Cilindrata (cc)')),
                ('dotazione_opzionale', models.TextField(blank=True, help_text='Lista di optional separati da virgole o newline.', verbose_name='Dotazione Opzionale')),
                ('foto_principale', models.ImageField(upload_to='veicoli_vendita/', verbose_name='Foto Principale')),
                ('data_pubblicazione', models.DateTimeField(auto_now_add=True, verbose_name='Data di Pubblicazione')),
                ('attivo', models.BooleanField(default=True, verbose_name='Disponibile per la Vendita')),
            ],
            options={
                'verbose_name': 'Veicolo in Vendita',
                'verbose_name_plural': 'Veicoli in Vendita',
                'ordering': ['-data_pubblicazione'],
            },
        ),
        migrations.CreateModel(
            name='VeicoloImmagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='veicoli_galleria/')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Testo Alt Immagine')),
                ('ordine', models.IntegerField(default=0)),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_foto', to='vendita.veicoloinvendita')),
            ],
            options={
                'verbose_name': 'Immagine Veicolo',
                'verbose_name_plural': 'Immagini Veicolo',
                'ordering': ['ordine'],
            },
        ),
    ]
