# Generated by Django 5.2.3 on 2025-09-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0002_veicoloinvendita_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='veicoloinvendita',
            name='is_quality',
            field=models.BooleanField(default=False, verbose_name='quality?'),
        ),
    ]
