# Generated by Django 5.2.3 on 2025-09-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0003_veicoloinvendita_is_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veicoloinvendita',
            name='colore_esterno',
        ),
        migrations.RemoveField(
            model_name='veicoloinvendita',
            name='colore_interno',
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='colore',
            field=models.CharField(blank=True, max_length=50, verbose_name='Colore'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='consumo_totale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consumo totale'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='marce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marce'),
        ),
        migrations.AlterField(
            model_name='veicoloinvendita',
            name='chilometraggio',
            field=models.IntegerField(verbose_name='Chilometraggio (Km)'),
        ),
    ]
