# Generated by Django 5.2.3 on 2025-09-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0004_remove_veicoloinvendita_colore_esterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veicoloinvendita',
            name='prezzo',
            field=models.CharField(max_length=100, verbose_name='Prezzo (CHF)'),
        ),
    ]
