# Generated by Django 5.2.3 on 2025-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0005_alter_veicoloinvendita_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veicoloinvendita',
            name='tipo_veicolo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo veicolo'),
        ),
        migrations.AlterField(
            model_name='veicoloinvendita',
            name='chilometraggio',
            field=models.CharField(verbose_name='Chilometraggio (Km)'),
        ),
        migrations.AlterField(
            model_name='veicoloinvendita',
            name='colore',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Colore'),
        ),
    ]
