# Generated by Django 5.2.3 on 2025-09-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0006_veicoloinvendita_tipo_veicolo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veicoloinvendita',
            name='box1',
            field=models.TextField(blank=True, null=True, verbose_name='Box 1'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='tit1',
            field=models.CharField(blank=True, default='Motore e trasmissione', null=True, verbose_name='Motore e trasmissione'),
        ),
        migrations.AlterField(
            model_name='veicoloinvendita',
            name='cilindrata',
            field=models.CharField(blank=True, null=True, verbose_name='Cilindrata'),
        ),
    ]
