# Generated by Django 5.2.3 on 2025-09-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0007_veicoloinvendita_box1_veicoloinvendita_tit1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veicoloinvendita',
            name='box2',
            field=models.TextField(blank=True, null=True, verbose_name='Box 2'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='box3',
            field=models.TextField(blank=True, null=True, verbose_name='Box 3'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='tit2',
            field=models.CharField(blank=True, default='Prestazioni e consumi', null=True, verbose_name='Prestazioni e consumi'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='tit3',
            field=models.CharField(blank=True, default='Comfort, sicurezza e altre dotazioni', null=True, verbose_name='Comfort, sicurezza e altre dotazioni'),
        ),
    ]
