# Generated by Django 5.2.3 on 2025-12-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0008_veicoloinvendita_box2_veicoloinvendita_box3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaVeicolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('messaggio', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('veicolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='vendita.veicoloinvendita')),
            ],
            options={
                'ordering': ['-data_invio'],
            },
        ),
    ]
