# Generated by Django 5.2.3 on 2025-12-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0009_richiestaveicolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veicoloinvendita',
            name='altezza',
            field=models.CharField(blank=True, null=True, verbose_name='Altezza'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='larghezza',
            field=models.CharField(blank=True, null=True, verbose_name='Larghezza'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='lunghezza',
            field=models.CharField(blank=True, null=True, verbose_name='Lunghezza'),
        ),
        migrations.AddField(
            model_name='veicoloinvendita',
            name='peso',
            field=models.CharField(blank=True, null=True, verbose_name='Peso totale'),
        ),
    ]
