# Generated by Django 5.2.3 on 2025-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita', '0010_veicoloinvendita_altezza_veicoloinvendita_larghezza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veicoloinvendita',
            name='potenza_cv',
            field=models.CharField(blank=True, null=True, verbose_name='Potenza (CV)'),
        ),
    ]
